### ISSUE TITLE
Issue if running a second polling listener

### ISSUE THREAD

**Issue by chrisspiegl** [Blitss/passport-telegram-official#2]
I really appreciate this implementation of the official Telegram oAuth system. I am currently developing a new little service and immediately chose to use it.

In my tests, I discovered that if I am running a listener myself, the server process that's running the express site (and the passport auth) will be in conflict with it all.

I wonder how this can be worked with. Does the oAuth actually need the Telegram SDK? Does it have to run polling? Is there a way around this?

But also Webhooks might be problematic as I already use those with the second listening process. Seems like this is not going to be all too easy. I hope you can help 💪.

**Comment by chrisspiegl** [comment]
Update: I looked deeper into it and found that this had nothing to do with this package actually. It's been a rouge process that was still running my telegram listener process. Thanks again for making this.

**Comment by blitss** [comment]
@spieglio Yes, it is. I used this name because telegram-passport was already used by another package with non-official authorization. So, it's just custom strategy for Passport.JS and https://telegram.org/blog/login.
