### ISSUE TITLE
[TypeScript] Importing the module

### ISSUE THREAD

**Issue by poeti8** [Blitss/passport-telegram-official#3]
I have a problem importing the package in TypeScript, although both of these methods work and actually import the module but still, TypeScript yells at me "What are you doing".

First method:
```js
import * as TelegramStrategy from 'passport-telegram-official';

// [ts] Module '".../node_modules/passport-telegram-official/dist/index"' resolves to a non-module entity and cannot be imported using this construct.
```

Second method:
```js
import TelegramStrategy = require('passport-telegram-official');

// [ts] Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
```

Seems like you're using `export = TelegramStrategy` which is kinda outdated. So if you use `export default` we can easily import it as default:
```js
export default TelegramStrategy;

// later
import TelegramStrategy from 'passport-telegram-official';
```

**Comment by blitss** [comment]
fixed in https://github.com/Blitss/passport-telegram-official/commit/75bc5b7dc897a3ef217ea7f1bea6b118582af0d1
