### ISSUE TITLE
TypeError: TelegramStrategy is not a constructor

### ISSUE THREAD

**Issue by BitDesert** [Blitss/passport-telegram-official#4]
Hi, maybe I'm wrong, but I have issues getting the Telegram login to work.

I included it via
`var TelegramStrategy = require('passport-telegram-official').Strategy;`
and used later in the code
`passport.use(new TelegramStrategy(`
but I get the following error: 

> TypeError: TelegramStrategy is not a constructor

What am I doing wrong? 
Thank you for your help!

Here is my code:
https://github.com/BitDesert/MyNanoNinja/blob/telegram-login/config/passport.js#L8
https://github.com/BitDesert/MyNanoNinja/blob/telegram-login/config/passport.js#L513

**Comment by blitss** [comment]
Hi,
I believe you should use another named/default export (I don't remember which one exactly):
`var TelegramStrategy = require('passport-telegram-official').TelegramStrategy;`

or ES6 export:
`import { TelegramStrategy } from 'passport-telegram-official'`

Hope it helps.
